name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with PYTHONPATH
        run: |
          python -m pytest src/tests --rootdir=src

      - name: Build Docker image
        run: |
          docker build -t sales_forecasting .

      - name: Run Docker container
        run: |
          docker run sales_forecasting

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag sales_forecasting ${{ secrets.DOCKER_USERNAME }}/sales_forecasting:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sales_forecasting:latest
